select bids.created,
       bids.updated,
       bids.deleted,
       bids.uuid,
       bids.auction_uuid,
       bids.response_type,
       bids.placed_at,
       bids.loss_reason as bid_loss_reason,
       bids.explanation,
       bids.ship_by_date,
       bids.supplier_id,
       bids.accepted_ship_by_date,
       bids.author_id,
       bids.margin, -- For debugging purposes only, do not use for reporting
       bids.margin_without_discount, -- This field will be used in auctions,
       bids.revision as bid_version, -- Used to calculate active vs 1st bid version.
       bids.subtotal_price_amount,
       bids.currency_code,
       bids.description,
       bids.lead_time,
       {{ varchar_to_boolean('has_changed_prices') }},
       {{ varchar_to_boolean('has_design_modifications') }},
       {{ varchar_to_boolean('has_changed_shipping_date') }},
       {{ varchar_to_boolean('is_active') }}
from {{ source('int_service_supply', 'new_bids') }} as bids
