select base.created_date,
       base.client_id,
       base.name,
       lower(coalesce(scl.first_quote_country_iso2, base.country_iso2))          as country_iso2, -- Coalesce the first_quote_country_iso2 as it is more accurate
       base.hs_company_id,
       case when base.hs_company_id is null then false else true end             as is_part_of_company,
       base.hs_contact_id,
       base.hutk_analytics_source,
       base.hutk_analytics_source_data_1,
       base.hutk_analytics_source_data_2,
       base.hutk_analytics_first_url,
       base.hutk_analytics_first_visit_timestamp,
       base.channel_type,
       base.channel,
       base.channel_grouped,
       base.lifecyclestage,
       base.first_page_seen,
       base.first_page_seen_grouped,
       base.first_page_seen_language,
       base.first_page_seen_query,
       nullif(json_extract_path_text(first_page_seen_query, 'utm_campaign'), '') as utm_campaign,
       nullif(json_extract_path_text(first_page_seen_query, 'utm_content'), '')  as utm_content,
       base.channel_drilldown_1,
       base.channel_drilldown_2,
       base.hubspot_owner_id,
       base.hubspot_owner_name,
       base.hubspot_owner_primary_team_name,
       base.bdr_owner_id,
       base.bdr_owner_name,
       base.hubspot_owner_assigned_date,
       base.contact_category,
       base.email_type,
       base.contact_source,
       base.country_name,
       base.market,
       base.region,
       base.continent,
       scl.became_lead_date,
       scl.became_mql_date,
       scl.became_sql_date,
       scl.became_opportunity_date,
       scl.became_customer_date,
       scl.total_order_closed_sales_usd,
       scl.first_quote_technology,
       scl.first_order_technology,
       scl.first_order_process_name,
       scl.second_order_closed_at,
       scl.new_customer_order_closed_sales_usd,
       scl.new_customer_precalc_margin_usd,
       ac.total_number_of_quotes,
       ac.total_number_of_closed_orders,
       ac.average_days_between_closed_orders,
       ac.median_days_between_closed_orders,
       ac.recent_closed_order_date,
       sca.became_company_mql_number,
       sca.became_company_opportunity_number,
       sca.became_company_customer_number,
       base.hs_lead_status,
       base.is_sales_qualified,
       base.job_role,
       base.advertising_gclid,
       base.advertising_msclkid,
       base.advertising_click_date,
       base.advertising_click_device,
       base.advertising_source,
       base.advertising_account_id,
       base.advertising_campaign_id,
       base.advertising_adgroup_id,
       base.advertising_keyword_id,
       base.advertising_campaign_group

from {{ ref('stg_dim_contacts') }} as base
        left join {{ ref('stg_contacts_lifecycle') }} as scl on scl.hubspot_contact_id = base.hs_contact_id
        left join {{ ref('stg_contacts_agg') }} as ac on base.hs_contact_id = ac.hubspot_contact_id
        left join {{ ref('stg_contacts_companies_agg') }} sca on sca.hubspot_contact_id = base.hs_contact_id