select base.created_date,
       base.client_id,
       base.name,
       lower(coalesce(agg_orders.first_submitted_order_country_iso2, base.country_iso2))   as country_iso2,
       base.hubspot_company_id,
       case when base.hubspot_company_id is null then false else true end             as is_part_of_company,
       base.hubspot_contact_id,
       base.hutk_analytics_source,
       base.hutk_analytics_source_data_1,
       base.hutk_analytics_source_data_2,
       base.hutk_analytics_first_url,
       base.hutk_analytics_first_visit_timestamp,
       base.channel_type,
       base.channel,
       base.channel_grouped,
       base.lifecyclestage,
       base.first_page_seen,
       base.first_page_seen_grouped,
       base.first_page_seen_language,
       base.first_page_seen_query,
       nullif(json_extract_path_text(first_page_seen_query, 'utm_campaign'), '') as utm_campaign,
       nullif(json_extract_path_text(first_page_seen_query, 'utm_content'), '')  as utm_content,
       base.channel_drilldown_1,
       base.channel_drilldown_2,
       base.hubspot_owner_id,
       base.hubspot_owner_name,
       base.hubspot_owner_primary_team_name,
       base.bdr_owner_id,
       base.bdr_owner_name,
       base.hubspot_owner_assigned_date,
       base.contact_category,
       base.email_type,
       base.contact_source,
       base.country_name,
       base.market,
       base.region,
       base.continent,
       base.hs_lead_status,
       base.is_sales_qualified,
       base.job_role,
       -- Advertising Fields
       ad.advertising_gclid,
       ad.advertising_msclkid,
       ad.advertising_click_date,
       ad.advertising_click_device,
       ad.advertising_source,
       ad.advertising_account_id,
       ad.advertising_campaign_id,
       ad.advertising_adgroup_id,
       ad.advertising_keyword_id,
       ad.advertising_campaign_group,
       -- Lifecycle Fields
       base.became_lead_at_contact,
       base.became_mql_at_contact,
       base.became_sql_at_contact,
       -- Order Aggregates
       agg_orders.became_opportunity_at_contact,
       agg_orders.became_customer_at_contact,
       agg_orders.second_order_closed_at_contact,
       agg_orders.recent_closed_order_at_contact,
       agg_orders.number_of_submitted_orders_contact,
       agg_orders.number_of_closed_orders_contact,
       agg_orders.closed_sales_usd_contact,
       agg_orders.closed_sales_usd_new_customer_contact,
       agg_orders.total_precalc_margin_usd_new_customer_contact,
       agg_orders.first_submitted_order_technology_contact,
       agg_orders.first_closed_order_technology_contact,
       agg_orders.first_closed_order_process_name_contact,
       agg_orders.average_days_between_closed_orders_contact,
       agg_orders.median_days_between_closed_orders_contact,
       -- Company Aggregates
       agg_companies.inside_mql_number,
       agg_companies.inside_opportunity_number,
       agg_companies.inside_customer_number

from {{ ref('stg_dim_contacts') }} as base
        left join {{ ref('stg_contacts_advertising_data') }} ad on base.hubspot_contact_id = ad.hubspot_contact_id
        left join {{ ref('agg_orders_contacts') }} as agg_orders on base.hubspot_contact_id = agg_orders.hubspot_contact_id
        left join {{ ref('stg_contacts_companies') }} as agg_companies on base.hubspot_contact_id = agg_companies.hubspot_contact_id
        