
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'hubs'
version: '1.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Model config
models:
  hubs:
    bing_ads:
      +schema: data_lake
      +tags: ["advertising", "bing"]
    data_lake:
      +schema: data_lake
      int_service_supply:
        materialized: view
        +tags: supply
        +bind: false
      freshdesk:
        +tags: freshdesk
    google_ads:
      +schema: data_lake
      +tags: ["advertising", "google"]
    hubspot:
      +schema: data_lake
      +tags: ["hubspot", "crm"]
    mapping:
      +schema: data_lake
    netsuite:
      +schema: data_lake
      +tags: ["netsuite", "finance"]
    netsuite_sandbox:
      +schema: data_lake
      +enabled: false
    reporting:
      +schema: reporting
      +materialized: table

# Seeds
seeds:
  +schema: seed_data
  states:
    +column_types:
      state: varchar(128)
      abbreviation: varchar(128)
      code: varchar(28)
  industries:
    +column_types:
      industry: varchar(128)
      industry_mapped: varchar(128)
  freshdesk_ticket_scope:
    +column_types:
      scope_id: int
      description: varchar(56)
    +tags: freshdesk
  freshdesk_conversation_source:
    +column_types:
      source_id: int
      decription: varchar(128)
    +tags: freshdesk
  freshdesk_ticket_priority:
    +column_types:
      priority_id: int
      description: varchar(56)
    +tags: freshdesk
  freshdesk_ticket_source:
    +column_types:
      source_id: int
      description: varchar(56)
    +tags: freshdesk
  freshdesk_ticket_status:
    +column_types:
      status_id: int
      description: varchar(56)
      created_by: varchar(56)
    +tags: freshdesk

# Snapshot configuration
snapshots:
  +target_schema: dbt_prod_snapshots # TODO: figure out proper way to run in user schema for testing

# Tests
# Can be found in models/schema.yml
