
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'hubs'
version: '1.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages" 

# Model config
models:
  hubs:
    external:
      bing_ads:
        +schema: data_lake
        +tags: ["advertising", "bing"]
      google_ads:
        +schema: data_lake
        +tags: ["advertising", "google"]
    data_lake:
      +schema: data_lake
      int_service_supply:
        materialized: view
        +tags: supply
        +bind: false
      freshdesk:
        +tags: freshdesk
    
    hubspot:
      +schema: data_lake
      +tags: ["hubspot", "crm"]
    mapping:
      +schema: data_lake
      +tags: ["adhoc"]
    netsuite:
      +schema: data_lake
      +tags: ["netsuite", "finance"]
    netsuite_sandbox:
      +schema: data_lake
      +enabled: false
    protolabs:
      +schema: protolabs  
    reporting: 
      +schema: reporting
      +materialized: table
      orders:
        +tags: ["orders"]
      contacts:
        +tags: ["contacts"]
      miscellaneous:
        +tags: ["adhoc"]


# Snapshot configuration
snapshots:
  +target_schema: dbt_prod_snapshots # TODO: figure out proper way to run in user schema for testing

# Tests
# Can be found in models/schema.yml

# Access
# On run-end read-only access is granted to the ro_group in Redshift on the target schema's contents.
on-run-end:
  - "{{ grant_select_on_schemas(schemas, 'ro_group') }}"
