name: 'dbt_core_network'
version: '1.0.1'
config-version: 2
dbt-cloud:
  project-id: 386544


# This setting configures which "profile" dbt uses for this project.
profile: 'my-snowflake-db'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Model config
models: #todo-migration-research: post-hooks were removed, check if this is an issue in Snowflake
  dbt_core_network:
    1_base:
      +schema: core
      +materialized: view
      +bind: false
      advertising:
        bing_ads:
          +tags: ["advertising", "bing"]
        google_ads:
          +tags: ["advertising", "google"]
      freshdesk:
        +tags: freshdesk
      hubspot:
        +tags: ["hubspot", "crm"]
      int_service_supply:
        +tags: supply
      netsuite:
        +tags: ["netsuite", "finance"]
      retool:
        +tags: ["retool"]
      typeform:
        +tags: ["typeform"]

    2_prep:
      +schema: core
      +materialized: view
      +bind: false


    3_staging:
      +schema: core
      +materialized: table
      orders:
        +tags: ["orders"]
      contacts:
        +tags: ["contacts"]
      +bind: false

    4_reporting:
      +schema: reporting
      +materialized: table

    5_protolabs:
      +schema: protolabs
      +bind: false
      +materialized: table
      +tags: protolabs

    6_miscellaneous:
      +schema: core
      +materialized: table
      adhoc_refresh:
        +tags: ["adhoc", "daily_exclusion"]
      weekly_refresh:
        +tags: ["weekly", "daily_exclusion"]
      backup_refresh:
        +tags: ["backup", "daily_exclusion"]

# Seeds schema
seeds:
  +schema: seed

# Snapshot configuration
snapshots:
  +target_schema: dbt_prod_snapshots

# Tests

# Variables
# These variables will need to be in H24 format!
vars:
  working_hour_start: 9
  working_hour_end: 18