select md5(concat('contact', con.hubspot_contact_id)) as client_id,
       con.hubspot_contact_id                         as hubspot_contact_id,
       null                                           as hubspot_company_id,
       'contact'                                      as type,
       name,
       became_mql_at,
       became_opportunity_at,
       became_customer_at,
       first_submitted_order_technology,
       first_closed_order_technology,
       first_page_seen_grouped,
       market,
       closed_sales_usd,
       closed_sales_usd_new_customer,
       con.channel_type,
       con.channel,
       con.channel_grouped,
       con.channel_drilldown_1,
       con.channel_drilldown_2,
       con.advertising_gclid,
       con.advertising_msclkid,
       con.advertising_click_date,
       con.advertising_click_device,
       con.advertising_source,
    --    con.utm_source as advertising_source,
       con.advertising_account_id,
       con.advertising_campaign_id,
       con.advertising_adgroup_id,
       con.advertising_keyword_id,
       con.advertising_campaign_group
from {{ ref('dim_contacts') }} con
where is_part_of_company = false
union
select md5(concat('company', com.hubspot_company_id)) as client_id,
       null                                           as hubspot_contact_id,
       com.hubspot_company_id                         as hubspot_company_id,
       'company'                                      as type,
       name,
       became_mql_at,
       became_opportunity_at,
       became_customer_at,
       first_submitted_order_technology,
       first_closed_order_technology,
       first_page_seen_grouped,
       market,
       closed_sales_usd,
       closed_sales_usd_new_customer,
       com.channel_type,
       com.channel,
       com.channel_grouped,
       com.channel_drilldown_1,
       com.channel_drilldown_2,
       com.advertising_gclid,
       com.advertising_msclkid,
       com.advertising_click_date,
       com.advertising_click_device,
       com.advertising_source,
       com.advertising_account_id,
       com.advertising_campaign_id,
       com.advertising_adgroup_id,
       com.advertising_keyword_id,
       com.advertising_campaign_group
from  {{ ref('dim_companies') }} com