select base.created_at,
       base.client_id,
       base.platform_user_id,
       base.name,
       base.country_iso2,
       base.hubspot_company_id,
       case when base.hubspot_company_id is null then false 
       when hc.hubspot_company_id is null then false else true end             as is_part_of_company,
       base.hubspot_contact_id,
       base.hutk_analytics_source,
       base.hutk_analytics_source_data_1,
       base.hutk_analytics_source_data_2,
       base.hutk_analytics_first_url,
       base.hutk_analytics_first_visit_timestamp,
       base.channel_type,
       base.channel,
       base.channel_grouped,
       base.lifecyclestage,
       base.first_page_seen,
       base.first_page_seen_grouped,
       base.first_page_seen_language,
       base.utm_campaign,
       base.utm_content,
       base.utm_source,
       base.utm_term,
       base.utm_medium,
       base.test_name,
       base.test_variant,            
       base.channel_drilldown_1,
       base.channel_drilldown_2,
       base.hubspot_owner_id,
       base.hubspot_owner_name,
       base.hubspot_owner_primary_team_name,
       base.bdr_owner_id,
       base.bdr_owner_name,
       base.bdr_campaign,
       base.hubspot_owner_assigned_at,
       base.last_contacted_at,
       base.is_strategic,
       base.email_type,
       base.contact_source,
       base.country_name,
       base.market,
       base.region,
       base.sub_region,
       base.continent,
       base.hs_lead_status,
       base.job_role,
       base.team_id,
       base.team_name,
       base.team_created_at,
       base.team_invited_at,
       base.team_invite_accepted_at,
       base.team_invite_status,
       base.is_team_member,
       base.platform_user_created_at,
       -- Advertising Fields
       ad.advertising_gclid,
       ad.advertising_msclkid,
       ad.advertising_source,
       ad.advertising_click_date,
       ad.advertising_click_device,
       ad.advertising_account_id,
       ad.advertising_campaign_id,
       ad.advertising_adgroup_id,
       ad.advertising_keyword_id,
       ad.advertising_campaign_group,
       -- Lifecycle Fields
       base.became_lead_at_contact                              as became_lead_at,
       base.became_mql_at_contact                               as became_mql_at,
       base.mql_technology                                      as mql_technology,
       base.mql_type,
       base.became_sql_at_contact                               as became_sql_at,
       -- Order Aggregates
       agg_orders.became_opportunity_at_contact                 as became_opportunity_at,
       agg_orders.became_customer_at_contact                    as became_customer_at,
       agg_orders.serie_two_order_created_at_contact            as serie_two_order_created_at,
       agg_orders.serie_two_order_closed_at_contact             as serie_two_order_closed_at,
       agg_orders.serie_three_order_created_at_contact          as serie_three_order_created_at,
       agg_orders.serie_three_order_closed_at_contact           as serie_three_order_closed_at,
       agg_orders.recent_order_created_at_contact               as recent_order_created_at,
       agg_orders.second_order_closed_at_contact                as second_order_closed_at,
       agg_orders.recent_closed_order_at_contact                as recent_closed_order_at,
       agg_orders.number_of_submitted_orders_contact            as number_of_submitted_orders,
       agg_orders.number_of_closed_orders_contact               as number_of_closed_orders,
       agg_orders.closed_sales_usd_contact                      as closed_sales_usd,
       agg_orders.closed_sales_usd_new_customer_contact         as closed_sales_usd_new_customer,
       agg_orders.total_precalc_margin_usd_contact_90d          as total_precalc_margin_usd_90d,
       agg_orders.total_precalc_margin_usd_contact_24m          as total_precalc_margin_usd_24m,
       agg_orders.total_precalc_margin_usd_new_customer_contact as precalc_margin_usd_new_customer,
       agg_orders.first_submitted_order_technology_contact      as first_submitted_order_technology,
       agg_orders.first_closed_order_technology_contact         as first_closed_order_technology,
       agg_orders.first_closed_order_process_name_contact       as first_closed_order_process_name,
       agg_orders.average_days_between_closed_orders_contact    as average_days_between_closed_orders,
       agg_orders.median_days_between_closed_orders_contact     as median_days_between_closed_orders,
       agg_orders.is_integration_contact                        as is_integration_contact,

       -- Company Aggregates
       agg_companies.inside_mql_number,
       agg_companies.inside_opportunity_number,
       agg_companies.inside_customer_number

from {{ ref('stg_dim_contacts') }} as base
        left join {{ ref('stg_contacts_advertising_data') }} ad on base.hubspot_contact_id = ad.hubspot_contact_id
        left join {{ ref('stg_contacts_companies') }} as agg_companies on base.hubspot_contact_id = agg_companies.hubspot_contact_id
        left join {{ ref('agg_orders_contacts') }} as agg_orders on base.hubspot_contact_id = agg_orders.hubspot_contact_id
        left join {{ ref('hubspot_companies') }}  hc on hc.hubspot_company_id = base.hubspot_company_id
        