select created,
       updated,
       deleted,
       address_id,
       address_line1,
       address_line2,
       administrative_area,
       lat,
       lon,
       locality,
       postal_code,
       country_id,
       country_name,
       country_alpha2_code,
       continent,
       company_name,
       first_name,
       last_name,
       email,
       timezone
from {{ ref('sources_network', 'gold_addresses') }}