select
auction_uuid,
order_uuid,
quote_uuid,
status,
auction_created_at,
auction_updated_at,
auction_deleted_at,
started_at,
finished_at,
last_processed_at,
_expected_sourcing_window_end_at as expected_sourcing_window_end_at,
auction_document_number,
auction_subtotal_price_amount,
technology_id,
technology_name,
base_margin,
base_margin_without_discount,
internal_support_ticket_opened_at,
internal_support_ticket_id,
winner_bid_uuid,
new_winner_bid_uuid,
is_rfq,
auction_type,
is_accepted_manually,
is_resourcing,
is_internal_support_ticket_opened
from {{ ref('network_services', 'gold_auctions') }}
