select created,
       updated,
       deleted,
       uuid,
       order_uuid,
       revision,
       is_last_version,
       status,
       finalized_at,
       document_number,
       shipping_address_id,
       billing_address_id,
       currency_code,
       price_multiplier,
       subtotal_price_amount,
       tax_price_amount,
       parent_uuid,
       payment_term,
       type,
       lead_time,
       company_entity_id,
       shipping_date,
       submitted_at,
       customer_purchase_order_uuid,
       signed_quote_uuid,
       technology_id,
       cross_docking_added_lead_time,
       split_off_from_quote_uuid,
       chargeable_shipping_weight_estimate_kg,
       is_eligible_for_local_sourcing,      
       is_local_sourcing,      
       is_eligible_for_cross_docking,
       is_admin,      
       requires_local_production,
       is_pl_pay_later_used,
       is_cross_docking_derived

from {{ ref('network_services', 'gold_documents') }} as docs