select supplier_id,
       auction_uuid,
       uuid,
       assigned_at,
       assigned_rank,       
       last_seen_at,
       first_seen_at,
       currency_code,
       margin,
       margin_without_discount,
       tax_rate,
       subtotal_price_amount,
       subtotal_price_amount_usd_cents,
       subtotal_price_amount_usd,
       tax_price_amount,
       tax_price_amount_usd,
       max_country_margin,
       company_entity_id,
       estimated_customs_price_amount,
       estimated_customs_price_amount_usd,
       shipping_estimate_amount_usd_cents,
       shipping_estimate_amount_usd,       
       estimated_customs_rate,
       ship_by_date,
       shipping_added_lead_time,
       dhl_shipping_price_estimate_amount_usd_cents,
       dhl_shipping_price_estimate_amount_usd,
       l1_shipping_margin_amount_usd_cents,
       l1_shipping_margin_amount_usd,  
       is_dismissed,
       is_automated_shipping_available,
       is_detected_similar,
       is_customer_requested_reorder,
       is_preferred_auction,
       is_restricted_auction,
       is_automatic_rfq,
       null as plan_to_bid_at --todo-migration-missing
    --    plan_to_bid_at 

from {{ ref('sources_network', 'gold_supplier_auctions') }}