select id,
       address_id,
       name,
       tax_number,
       created,
       updated,
       deleted,
       currency_code,
       unit_preference,
       monthly_order_value_target,
       tax_number_2,
       default_shipping_carrier_id,
       is_eligible_for_vqc,
       is_suspended,
       is_accepting_auctions,
       send_automatic_rfq,
       allow_for_rfq,
       country_id,
       country_name,
       address_first_name,
       address_last_name,
       full_address,
       locality,
       address_postal_code,
       address_latitude,
       address_longitude,
       address_timezone

from {{ ref('network_services', 'gold_suppliers') }}