select 
    created_at,
    last_active_at as last_sign_in_at,
    user_id,
    uuid,
    country_code,
    first_name,
    last_name,
    full_name,
    email,
    email_domain,
    is_internal,
    is_test,
    is_protolabs,
    is_anonymized,
    settings,
    is_email_verified,
    signup_source,
    hubspot_contact_id,
    team_id,
    team_name,
    team_created_at
from {{ ref('network_services', 'gold_users') }}