select created,
       updated,
       deleted,
       address_id,
       address_line1,
       nullif(address_line2, '') address_line2,
       administrative_area,
       dependent_locality,
       formatted,
       locality,
       locality_name,
       postal_code,
       sorting_code,
       country_id,
       company_name,
       first_name,
       last_name,
       email,
       phone,
       industry,
       timezone
from int_service_supply.addresses