select created,
       updated,
       deleted,
       address_id,
       address_line1,
       nullif(address_line2, '') address_line2,
       administrative_area,
       dependent_locality,
       formatted,
       locality,
       locality_name,
       postal_code,
       sorting_code,
       country_id,
       company_name,
       md5(first_name) as first_name_hashed,
       md5(last_name) as last_name_hashed,
       md5(email) as email_hashed,
       md5(phone) as phone_hashed,
       industry,
       timezone
from int_service_supply.addresses