select created,
       updated,
       deleted,
       id,
       uuid,
       order_uuid,
       revision,
       status,
       finalized_at,
       {{ varchar_to_boolean('is_admin') }},
       document_number,
       contact_preference,
       tax_number,
       shipping_address_id,
       billing_address_id,
       payment_reference,
       currency_code,
       price_multiplier,
       subtotal_price_amount,
       tax_price_amount,
       tax_rate,
       turnaround_time,
       description,
       admin_description,
       {{ varchar_to_boolean('is_instant_payment') }},
       parent_uuid,
       payment_term,
       type,
       lead_time,
       document_file_uuid,
       company_entity_id,
       payment_details_id,
       shipping_date,
       terms_and_conditions_id,
       quickbooks_upload_id,
       submitted_at,
       requires_local_production,
       tax_number_2,
       {{ varchar_to_boolean('is_admin_only') }},
       archive_file_uuid,
       customer_purchase_order_reference,
       customer_purchase_order_uuid,
       signed_quote_uuid,
       tax_category_id,
       technology_id,
       {{ varchar_to_boolean('tax_category_override') }},
       {{ varchar_to_boolean('is_cross_docking') }},
       cross_docking_added_lead_time,
       name,
       customer_edited_at,
       technical_drawing_anonymization_started_at
from int_service_supply.cnc_order_quotes