select created,
       updated,
       deleted,
       id,
       hubspot_deal_id,
       uuid,
       reorder_original_order_uuid,
       user_id,
       quote_uuid,
       session_id,
       status,
       {{ varchar_to_boolean('is_admin') }},
       {{ varchar_to_boolean('is_strategic') }},
       delivered_at,
       shipped_at,
       expected_shipping_date,
       hub_id,
       legacy_order_id,
       legacy_status,
       station_id,
       completed_at,
       billing_request_id,
       {{ varchar_to_boolean('is_automated_shipping_available') }},
       support_ticket_id,
       number,
       {{ varchar_to_boolean('should_create_auction') }},
       cancellation_reason_id,
       in_production_at,
       promised_shipping_date,
       accepted_at,
       description,
       shipped_to_warehouse_at
from int_service_supply.cnc_orders