select created,
       updated,
       deleted,
       country_id,
       name,
       alpha2_code,
       continent,
       decode(is_in_eu, 'true', True, 'false', False) as is_in_eu,
       decode(has_payment_embargo, 'true', True, 'false', False) as has_payment_embargo,
       currency_code,
       decode(is_in_efta, 'true', True, 'false', False) as is_in_efta,
       coordinates,
       lat,
       lon
from int_service_supply.countries