{{
    config(
        materialized='table'
    )
}}

select created,
       updated,
       deleted,
       id,
       uuid,
       quote_uuid,
       upload_id,
       type,
       quantity,
       auto_price_original_amount,
       price_amount,
       price_variations,
       unit,
       custom_material_subset_name,
       finish_slug,
       custom_finish_name,
       title,
       description,
       admin_description,
       auto_price_amount,
       unit_price_amount,
       material_subset_id,
       material_id,
       process_id,
       technology_id,
       exceeds_standard_tolerances,
       has_threads,
       parent_uuid,
       custom_tolerance,
       decode(should_quote_manually, 'true', True, 'false', False) as should_quote_manually,
       decode(has_technical_drawings, 'true', True, 'false', False) as has_technical_drawings,
       auto_tooling_price_amount,
       auto_tooling_price_original_amount,
       tooling_price_amount,
       infill,
       layer_height,
       material_color_id,
       lead_time_options,
       legacy_id,
       branded_material_id,
       part_orientation_additional_notes,
       part_orientation_vector,
       weight_in_grams,
       tax_code,
       tax_details,
       tax_price_amount,
       tax_price_exempt_amount,
       upload_properties,
       price_multiplier,
       requires_specific_gate_position,
       requires_specific_parting_line,
       requires_rapid_tooling,
       decode(is_visible_to_supplier, 'true', True, 'false', False) as is_visible_to_supplier,
       commodity_code,
       shipping_option_id,
       target_margin,
       commodity_code_source,
       discount_id,
       custom_tolerance_unit,
       tolerance_id,
       custom_tolerance,
       decode(is_cosmetic, 'true', True, 'false', False) as is_cosmetic,
       estimated_price_amount,
       estimated_price_original_amount,
       thickness
from int_service_supply.line_items