select material_subset_id,
       material_id,
       process_id,
       composite_id,
       name,
       short_description,
       order_within_process,
       image_id,
       slug,
       slug_scope,
       decode(is_available_in_auctions, 'true', True, 'false', False)   as is_available_in_auctions,
       decode(is_available_to_suppliers, 'true', True, 'false', False)  as is_available_to_suppliers,
       decode(has_ral_and_pantone_colors, 'true', True, 'false', False) as has_ral_and_pantone_colors,
       density,
       alternative_name,
       show_in_material_pages,
       anodizing_compatibility,
       common_applications,
       corrosion_resistance,
       electrical_resistivity,
       elongation_at_break,
       engineering_comment,
       esd_safety,
       hardness,
       magnetism,
       maximum_service_temperature,
       post_processing,
       thermal_conductivity,
       thermal_expansion_coefficent,
       ultimate_tensile_strength,
       uv_resistance,
       weldability,
       yield_strength,
       youngs_modulus,
       datasheet_id,
       flexural_strength,
       glass_transition_temperature,
       heat_deflection,
       izod_impact,
       melting_point
from int_service_supply.material_subsets