select created,
       updated,
       deleted,
       process_id,
       name,
       nullif(about, '-')                     as about,
       slug,
       slug_scope,
       benefits,
       limitations,
       nullif(max_part_size, '-')             as max_part_size,
       price,
       tolerance,
       nullif(turnaround_time, '-')           as turnaround_time,
       nullif(wall_thickness, '-')            as wall_thickness,
       header_image_id,
       technology_id,
       infill_percentages,
       nullif(layer_height_z_resolution, '-') as layer_height_z_resolution,
       layer_height_z_resolution_default,
       layer_height_z_resolutions

from {{ source('int_service_supply', 'processes') }}