with tickets as (
    select *, row_number() over (partition by id order by updated_at desc, load_timestamp desc nulls last) as rn
    from landing.freshdesk_tickets_landing
)
select tickets.id,
       tickets.type,
       tickets.due_by,
       tickets.fr_due_by,
       tickets.is_escalated,
       tickets.created_at,
       tickets.updated_at,
       tickets.fr_escalated,
       nullif(regexp_substr(subject, 'C-[a-z0-9]{5,}', 1, 1, 'i'), '')      as derived_document_number,
       nullif(trim(regexp_substr(subject, 'po-\\w+-?\\w?', 1, 1, 'i')), '') as derived_po_number,
       coalesce(
               custom_fields_cf_hubspot_id,
               nullif(reverse(regexp_replace(split_part(reverse(custom_fields_cf_hubspot_deal_url), '/', 1), '[^0-9]',
                                             '')), '')
           )                                                                as hubspot_deal_id,
       tickets.status,
       ftstam.description                                                   as status_description,
       tickets.spam,
       tickets.email_config_id::bigint                                      as email_config_id,
       coalesce(tickets.group_id, ftgb20200401.id)                          as group_id,
       tickets.priority,
       ftpm.description                                                     as priority_description,
       tickets.requester_id,
       tickets.responder_id::bigint                                         as responder_id,
       tickets.source,
       ftsm.description                                                     as source_description,
       tickets.company_id::float::bigint                                    as company_id,
       tickets.subject,
       tickets.association_type,
       tickets.product_id,
       tickets.associated_tickets_count,
       tickets.tags,
       tickets.nr_due_by,
       tickets.nr_escalated,
       tickets.to_emails,
       tickets.cc_emails,
       tickets.fwd_emails,
       tickets.reply_cc_emails,
       tickets.ticket_cc_emails,
       tickets.custom_fields_follow_email_sent,
       tickets.custom_fields_cf_liability_cnc_disputes,
       tickets.custom_fields_cf_qualified,
       tickets.custom_fields_cf_location,
       tickets.custom_fields_cf_entity,
       tickets.custom_fields_cf_order_value,
       tickets.custom_fields_cf_finance_category,
       tickets.custom_fields_cf_deal_owner,
       tickets.custom_fields_cf_ticketsubcategorised,
       tickets.custom_fields_cf_categories,
       tickets.custom_fields_cf_answered_in_the_new_faq,
       tickets.custom_fields_order_id,
       tickets.custom_fields_cf_ticket_category,
       tickets.custom_fields_cf_hubspot_id,
       tickets.custom_fields_cf_country,
       tickets.custom_fields_cf_logistics_category,
       tickets.custom_fields_cf_3d_hubs_tag,
       tickets.custom_fields_cf_purchase_order_url,
       tickets.custom_fields_cf_hubspot_deal_url,
       tickets.custom_fields_cf_order_parts_download_url,
       tickets.custom_fields_cf_first_response,
       tickets.custom_fields_cf_value,
       tickets.custom_fields_cf_order_technology,
       tickets.custom_fields_cf_supplier_country,
       tickets.custom_fields_cf_supplier_ticket_id,
       tickets.custom_fields_cf_supplier_name,
       tickets.custom_fields_cf_customer_email,
       tickets.stats_agent_responded_at,
       tickets.stats_requester_responded_at,
       tickets.stats_first_responded_at,
       tickets.stats_status_updated_at,
       tickets.stats_reopened_at,
       tickets.stats_resolved_at,
       tickets.stats_closed_at,
       tickets.stats_pending_since,
       decode(tickets.rn, 1, True)                                          as _is_latest,
       tickets.load_timestamp                                               as _load_timestamp
from tickets
         left outer join {{ ref('freshdesk_ticket_source') }} ftsm
                         on tickets.source = ftsm.source_id
         left outer join {{ ref('freshdesk_ticket_priority') }} ftpm
                         on tickets.priority = ftpm.priority_id
         left outer join {{ ref('freshdesk_ticket_status') }} ftstam
                         on tickets.status = ftstam.status_id
         left outer join landing.freshdesk_tickets_groups_backup_20200401 ftgb20200401 -- This table may need to be migrated to /data
                         on tickets.id = ftgb20200401.ticket_id