-- This model includes only line items from the main quote of an order, it queries from fact_line_items
-- and self joins in order to obtain the costs of the matching line item in the purchase order.

-- Line Items from the Active PO, in some rare cases an order has > 1 active POs.
with active_po_line_items as (
     select *,
            dense_rank() over (partition by order_uuid order by quote_uuid) as dr 
     from {{ ref('fact_line_items') }} 
     where true
        and is_active_po
)

select 
    order_uuid,
    document_uuid,
    document_type,
    document_revision,
    is_order_quote,
    is_active_po,
    created_date,
    li_updated_at,
    line_item_id,
    line_item_number,
    line_item_uuid,
    quote_uuid,
    upload_id,
    correlation_uuid,
    technology_id,
    technology_name,
    material_id,
    material_subset_id,
    process_id,
    process_name,
    material_color_id,
    branded_material_id,
    shipping_option_id,
    line_item_type,
    custom_material_subset_name,
    has_custom_material_subset,
    custom_surface_finish_name,
    has_custom_finish,
    line_item_description,
    has_customer_note,
    admin_description,
    line_item_title,
    has_technical_drawings,
    lead_time_options,
    part_orientation_additional_notes,
    part_orientation_vector,
    upload_properties,
    unit,
    quantity,
    has_threads,
    has_fits,
    has_internal_corners,
    has_part_marking,
    infill,
    layer_height,
    is_cosmetic,
    material_name,
    is_expedited,
    is_vqced,
    commodity_code,
    tiered_tolerance,
    general_tolerance,
    custom_tolerance,
    custom_tolerance_unit,
    material_type_name,
    material_subset_name,
    material_density_g_cm3,
    material_color_name,
    branded_material_name,
    surface_finish_name,
    cosmetic_type,
    dispute_created_at,
    is_dispute,
    dispute_description,
    dispute_affected_parts_quantity,
    has_tolerance_issue,
    has_incomplete_order_issue,
    has_missing_threads_issue,
    has_other_issue,
    has_surface_finish_issue,
    has_incorrect_material_issue,
    has_parts_damaged_issue,
    complaint_created_at,
    is_complaint,
    complaint_is_valid,
    complaint_is_conformity_issue,
    complaint_outcome_customer,
    complaint_outcome_supplier,
    complaint_resolution_at,
    complaint_created_by,
    complaint_reviewed_by,
    complaint_comment,
    complaint_type,
    complaint_liability,
    corrective_action_plan_needed,
    qc_comment,
    part_depth_cm,
    part_width_cm,
    part_height_cm,
    part_longest_dimension,
    part_bounding_box_volume_cm3,
    part_smallest_bounding_box_volume_cm3,
    part_volume_cm3,
    part_weight_g,
    line_item_total_bounding_box_volume_cm3,
    line_item_total_smallest_bounding_box_volume_cm3,
    line_item_total_volume_cm3,
    line_item_weight_g,
    auto_price_amount,
    line_item_price_amount,
    line_item_price_amount_usd,
    line_item_price_amount_source_currency,
    line_item_price_amount_manually_edited,
    line_item_estimated_l1_customs_amount_usd_no_winning_bid,
    quoting_package_version

    from active_po_line_items 
    where dr = 1
