with complete_orders as (
  
-- This unions the fact_orders table together with the missing_orders table which is a static table
-- that contains deals from both Drupal and Hubspot that are not found in service supply (~9K).

  {{ dbt_utils.union_relations(
    relations=[ref('fact_orders'), source('data_lake', 'legacy_orders')]
) }}

-- The DBT union relations package unions tables even when they have different widths and column orders

)

select 

-- Fields Matching (While Testing)

po_active_amount_usd as active_po_amount_usd,
po_active_document_number as active_po_document_number,
auction_created_at as auction_create_date,
auction_finished_at as auction_finished_date,
auction_status as auction_status,
bdr_owner_id as bdr_owner_id,
bdr_owner_name as bdr_owner_name,
bdr_owner_primary_team_name as bdr_owner_primary_team_name,
became_customer_date_contact as became_customer_date_contact,
date_trunc('day', became_opportunity_date_contact) as became_opportunity_date_contact,
-- cancellation_reason as cancellation_reason, -- Definition was changed, not comparable
order_cancelled_at as cancelled_at,
change_request_freshdesk_ticket_id as change_request_freshdesk_ticket_id,
change_request_status as change_request_status,
destination_city as city,
order_closed_at as closed_date,
closed_deal_days_between_previous_deal_contact as closed_deal_days_between_previous_deal_contact,
-- closed_deal_days_between_previous_deal_from_delivery_contact as closed_deal_days_between_previous_deal_from_delivery_contact, -- Old KPI
closed_deal_number_contact as closed_deal_number_contact,
hubspot_closed_lost_reason as closed_lost_reason,
order_closed_amount_usd as closed_sales_usd,
hubspot_company_name as company_name,
order_completed_at as completed_date,
destination_country_iso2 as country_iso2,
destination_country as country_name,
cross_dock_city as cross_dock_city,
cross_dock_country as cross_dock_country,
customer_success_representative_name as customer_success_representative_name,
hubspot_deal_category as deal_category,
delay_liability as delay_liability,
delay_status as delay_status,
order_delivered_at as delivered_date,
delivered_to_cross_dock_at as delivered_date_to_cross_dock,
derived_delivered_at as derived_delivery_date,
dispute_created_at as dispute_created_at,
dispute_liability as dispute_liability,
dispute_requested_outcome as dispute_requested_outcome,
dispute_resolution_at as dispute_resolution_date,
dispute_resolution_time_hours as dispute_resolution_time_in_hours,
dispute_status as dispute_status,
dispute_type as dispute_type,
order_document_number as document_number,
estimated_delivery_to_cross_dock as estimated_delivery_to_cross_dock,
estimated_delivery_to_customer as estimated_delivery_to_customer,
first_bdr_owner_date_company as first_bdr_owner_date,
order_first_completed_at as first_completed_date,
first_dispute_resolution_type as first_dispute_resolution_type,
first_time_quote_sent_at as first_time_quote_sent_date,
first_time_response_at as first_time_response_date,
full_delivered_at as full_delivered_date,
auction_is_reviewed_manually as has_auction_manually_reviewed,
has_change_request as has_change_request,
has_consistent_shipping_info as has_consistent_shipping_info,
has_custom_finish as has_custom_finish,
has_custom_material_subset as has_custom_material,
quote_first_created_by_admin as has_first_quote_created_by_admin,
has_manual_quote_review as has_manually_reviewed_quote_request,
quote_first_has_part_without_automatic_pricing as has_part_without_automatic_pricing,
has_admin_created_quote as has_quote_created_by_admin,
is_hubspot_high_risk as high_risk,
hubspot_amount_usd as hubspot_amount_usd,
hubspot_closed_at as hubspot_closedate,
hubspot_company_id as hubspot_company_id,
hubspot_company_source as hubspot_company_source,
hubspot_contact_id as hubspot_contact_id,
hubspot_deal_id as hubspot_deal_id,
hubspot_dealstage_mapped as hubspot_dealstage_mapped,
hubspot_dealstage_mapped_sort_index as hubspot_dealstage_mapped_sort_index,
hubspot_estimated_close_amount_usd as hubspot_estimated_close_amount_usd,
hubspot_owner_assigned_at as hubspot_owner_assigned_date,
hubspot_owner_id as hubspot_owner_id,
hubspot_owner_name as hubspot_owner_name,
hubspot_owner_primary_team_name as hubspot_owner_primary_team_name,
hubspot_purchasing_manager as hubspot_purchasing_manager,
hubspot_sourcing_owner_id as hubspot_sourcing_owner_id,
hubspot_sourcing_owner_name as hubspot_sourcing_owner_name,
hubspot_technical_review_owner as hubspot_technical_review_owner,
in_review_reason as in_review_reason,
in_review_type as in_review_type,
auction_is_accepted_manually as is_accepted_manually_auction,
contact_email_from_hubs as is_address_email_from_hubs,
is_closed as is_closed_won,
is_auto_payment as is_collected_using_auto_payment,
order_quote_is_cross_docking as is_cross_docking,
is_disputed as is_disputed,
is_expedited_shipping as is_expedited_shipping,
is_hubspot_strategic_company as is_hubspot_strategic_company,
is_hubspot_strategic_deal as is_hubspot_strategic_deal,
is_instant_payment as is_instant_payment,
is_new_customer_contact as is_new_customer_contact,
is_rda_sourced as is_rda_sourced,
is_recognised as is_recognized,
is_resourced as is_resourced,
order_has_rfq as is_rfq,
is_shipped_on_time_by_supplier as is_shipped_on_time_by_mp,
is_shipped_on_time_to_customer as is_shipped_on_time_to_customer,
is_sourced as is_sourced,
order_is_svp as is_svp,
order_has_technical_review as is_technical_review,
order_is_underquoted as is_underquoted,
order_last_completed_at as last_completed_date,
destination_market as market,
mechanical_engineer_id as mechanical_engineer_id,
mechanical_engineer_name as mechanical_engineer_name,
number_of_packages as no_of_packages,
number_of_quote_versions as number_of_quote_versions,
number_of_quote_versions_by_admin as number_of_quote_versions_by_admin,
number_of_rfq_requests as number_of_suppliers_rfq_requests,
number_of_rfq_responded as number_of_suppliers_rfq_responded,
-- po_active_company_entity as order_active_po_company_entity, -- We accepted the difference, it has more values in DBT
po_active_uuid as order_active_po_quote_uuid,
po_active_shipping_usd as order_active_po_shipping_usd,
order_created_at,
order_quote_finalised_at as order_quote_finalized_date,
order_quote_lead_time as order_quote_lead_time,
order_recognised_at as order_recognized_date,
order_status as order_status,
supply_last_review_completed_at as order_technical_review_completed_at,
supply_first_review_submitted_at as order_technical_review_submitted_at,
order_uuid as order_uuid,
partner_support_representative_name as partner_support_representative_name,
payment_method as payment_method,
po_first_shipping_usd as po_first_shipping_usd,
line_item_process_id as process_id,
line_item_process_name as process_name,
qc_inspection_result as qc_inspection_result,
company_entity as quote_company_entity,
date_trunc('day', order_submitted_at) as quote_submitted_date,
order_submitted_amount_usd as quote_subtotal_amount_usd,
-- refund_reason as refund_reason, low to null usage in Looker, the field just delivers one category so is a bit useless, it can be added again later if requested
destination_region as region,
reorder_original_order_uuid as reorder_original_order_uuid,
order_quote_requires_local_sourcing as requires_local_sourcing,
po_active_promised_shipping_at_by_supplier as ship_date_promised_by_supplier,
order_promised_shipping_at_to_customer as ship_date_promised_to_customer,
order_shipped_at as shipped_date,
shipped_from_cross_dock_at as shipped_date_from_cross_dock,
shipping_by_supplier_delay_days as shipping_by_supplier_days_delay,
destination_latitude as shipping_latitude,
destination_longitude as shipping_longitude,
shipping_to_customer_delay_days as shipping_to_customer_days_delay,
shipping_amount_usd as shipping_usd,
sourced_cost_usd as sourced_cost_usd,
order_sourced_at as sourced_date,
order_sourced_amount_usd as sourced_sales_usd,
destination_us_state as state,
origin_country as supplier_country_name,
supplier_id as supplier_id,
origin_latitude as supplier_latitude,
origin_longitude as supplier_longitude,
supplier_name as supplier_name,
order_technology_id as technology_id,
order_technology_name as technology_name,
winning_bid_uuid as winning_bid_uuid,
order_quote_uuid as winning_quote_uuid
-- order_is_legacy as is_legacy_order
-- order_data_source as _data_source

from complete_orders as orders
left join {{ ref('agg_orders') }} as agg_orders using(order_uuid) 
where true
and (order_quote_status = 'cart') is not true 
and order_data_source = 'supply'
-- or order_data_source in ('hubspot', 'drupal') -- To be added later
