version: 2

models:
  - name: fact_supplier_auction_interactions
    columns:
      - name: supplier_auction_uuid
        tests:
          - unique
          - not_null
  - name: dim_supplier_technologies
    columns:
      - name: supplier_id
        tests:
          - unique