version: 2

sources:

  - name: _3d_hubs
    tables:
      - name: supply_quote_updated
      - name: frontend_email_wall_submitted

  - name: adwords
    tables:
      - name: click_performance_reports

  - name: ext_adwords
    tables:
      - name: accounts
      - name: ad_groups
      - name: ad_groups__labels
      - name: campaigns__labels
      - name: campaign_performance_report
      - name: campaigns
      - name: click_performance_report
      - name: keywords_performance_report

  - name: ext_bing
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: keyword_performance_report


  - name: data_lake
    tables:
      - name: hubspot_engagements
      - name: hubspot_deals
      - name: hubspot_contacts
      - name: hubspot_companies
      - name: hubspot_deal_dealstage_history
      - name: hubspot_owners
      - name: hubspot_owners_teams
      - name: exchange_rate_spot_daily
      - name: google_search_console
      - name: supply_countries_markets_mapping
      - name: static_seo_page_group
      - name: static_seo_targets      
        freshness:
          warn_after: {count: 2, period: day}
        loaded_at_field: load_timestamp
      - name: hubspot_email_wall_submissions_20210423
      - name: adhoc_drupal_closed_sales_20191211
      - name: supply_cross_docking_tracking_details_20200911

  - name: int_service_supply
    tables:
      - name: cancellation_reasons
      - name: dispute_line_items_issues
      - name: lead_time_tiers
      - name: line_items
      - name: refund_requests

  - name: reporting
    tables:
      - name: cube_deals

models:
  - name: fact_supplier_auction_interactions
    columns:
      - name: supplier_auction_uuid
        tests:
          - unique
          - not_null

  - name: fact_disputes
    columns:
      - name: order_uuid
        tests:
          - unique

  - name: append_orders_rda
    columns:
      - name: order_uuid
        tests:
          - unique