version: 2

sources:

  - name: adwords
    tables:
      - name: click_performance_reports

  - name: ext_adwords
    tables:
      - name: accounts
      - name: ad_groups
      - name: ad_groups__labels
      - name: campaigns__labels
      - name: campaign_performance_report
      - name: campaigns
      - name: click_performance_report
      - name: keywords_performance_report

  - name: ext_bing
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns


  - name: data_lake
    tables:
      - name: hubspot_engagements
      - name: hubspot_deals
      - name: hubspot_contacts
      - name: hubspot_companies
      - name: hubspot_owners
      - name: hubspot_owners_teams
      - name: exchange_rate_spot_daily
      - name: google_search_console
      - name: supply_countries_markets_mapping
      - name: static_seo_page_group
      - name: static_seo_targets
      
        freshness:
          warn_after: {count: 2, period: day}
        loaded_at_field: load_timestamp

  - name: int_service_supply
    tables:
      - name: dispute_line_items_issues
      - name: line_items

  - name: reporting
    tables:
      - name: cube_deals
      - name: agg_advertising_spend_monthly
models:
  - name: fact_supplier_auction_interactions
    columns:
      - name: supplier_auction_uuid
        tests:
          - unique
          - not_null

  - name: fact_disputes
    columns:
      - name: order_uuid
        tests:
          - unique

  - name: agg_quote_transactions
    columns:
      - name: quote_uuid
        tests: