version: 2


###########
# SOURCES #
###########

sources:

  - name: _3d_hubs
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: received_at
    tables:
      - name: supply_quote_updated
      - name: frontend_email_wall_submitted

  - name: adwords
    tables:
      - name: click_performance_reports

  - name: data_lake
    tags: ['data_lake']
    tables:
      - name: full_order_history_events
      - name: hubspot_engagements
        loaded_at_field: load_timestamp
      - name: hubspot_email_wall_submissions_20210423
      - name: legacy_contacts
      - name: exchange_rate_spot_daily
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: load_timestamp
      - name: google_search_console
        freshness:
          warn_after: {count: 5, period: day}
          error_after: {count: 6, period: day}
        loaded_at_field: date
      - name: btyd
        freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 14, period: day}
        loaded_at_field: snapshot_date
      - name: customer_tiering
        freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
        loaded_at_field: snapshot_at
      - name: supply_countries_markets_mapping
      - name: static_seo_page_group
      - name: static_seo_targets
      - name: supply_cross_docking_tracking_details_20200911
      - name: legacy_orders
      - name: freshdesk_groups_legacy_20200401
      - name: dim_dates

  - name: dbt_backups
    tables:
      - name: backup_fact_contribution_margin
      - name: backup_fact_orders
      - name: backup_full_order_history_events
      - name: backup_dim_companies
      - name: backup_dim_contacts   

  - name: ext_adwords
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: click_performance_report
      - name: keywords_performance_report

  - name: ext_aftership_bv
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: data
      - name: data__msg__checkpoints
    
  - name: ext_aftership_llc
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: data
      - name: data__msg__checkpoints

  - name: ext_bing
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: keyword_performance_report

  - name: ext_hubspot_webhooks
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: data

  - name: ext_raw
    tables:
      - name: hubspot_pages
        freshness:
          warn_after: {count: 48, period: hour}
          error_after: {count: 72, period: hour}
        loaded_at_field: "date::timestamp"
      - name: hubspot_owners

  - name: ext_google_ads_console
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: click_performance_report
      - name: keywords_performance_report

  - name: ext_gsheets
    loaded_at_field: _sdc_received_at
    tables:
      - name: marketing_ahrefs
      - name: marketing_share_of_voice
      - name: marketing_youtube
      - name: hr_bamboo_employees

  - name: ext_hubspot
    tables:
      - name: contacts
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: _sdc_received_at
      - name: companies
        freshness:
          warn_after: {count: 24, period: hour} 
          error_after: {count: 48, period: hour}
        loaded_at_field: _sdc_received_at
      - name: campaigns
      - name: deals
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: _sdc_received_at
      - name: deals__associations__associatedcompanyids
      - name: deals__associations__associatedvids
      - name: email_events
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: _sdc_received_at
           
  - name: ext_netsuite
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: currencyrate
      - name: transaction
      - name: customer
      - name: transaction__itemlist__item

  - name: int_greenhubs
    tables:
      - name: co2_emissions

  - name: int_logistics
    tables:
      - name: automated_shipping_customs_information

  - name: int_service_supply
    tables:
      - name: addresses
      - name: auctions
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: started_at      
      - name: bids
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: placed_at       
      - name: bids_bid_reasons
      - name: bid_reasons
      - name: billing_requests
        freshness:
          warn_after: {count: 31, period: day}
          error_after: {count: 33, period: day}
        loaded_at_field: created            
      - name: branded_materials
      - name: cancellation_reasons
      - name: cnc_order_parts_inspection_attachments
      - name: cnc_order_quote_attachments
      - name: cnc_orders
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: created
      - name: cnc_order_quotes
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: started_at       
      - name: company_entities
      - name: complaint_reasons
      - name: complaint_type_reasons
      - name: complaint_type_reasons_association
      - name: complaint_types
      - name: complaints
        freshness:
          warn_after: {count: 4, period: day}
          error_after: {count: 7, period: day}
        loaded_at_field: created      
      - name: countries
      - name: currencies      
      - name: discount_codes
      - name: discounts
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: created      
      - name: dispute_issues
      - name: dispute_line_items
      - name: dispute_line_items_issues
      - name: disputes
        freshness:
          warn_after: {count: 4, period: day}
          error_after: {count: 7, period: day}
        loaded_at_field: created      
      - name: external_orders
        freshness: null # To be added when more volume
        loaded_at_field: created      
      - name: financial_settings
      - name: lead_time_tiers
      - name: line_items
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: started_at        
      - name: matching_scores
      - name: material_colors
      - name: material_finishes
      - name: material_subsets
      - name: material_subsets_region_settings
      - name: materials
      - name: materials_material_finishes
      - name: netsuite_customers
      - name: order_change_requests
      - name: order_delays
        freshness:
          warn_after: {count: 2, period: day}
          error_after: {count: 4, period: day}
        loaded_at_field: created      
      - name: order_history_events
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: created      
      - name: order_review_answers
      - name: order_review_questions
      - name: packages
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: created      
      - name: package_line_items
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: created      
      - name: processes
      - name: purchase_orders
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: created      
      - name: question_groups
      - name: question_types
      - name: questions
      - name: quicklinks_tracking
      - name: quote_docusign_requests
      - name: refund_reasons
      - name: refund_requests
      - name: refunds
      - name: replies
      - name: reply_options
      - name: roles      
      - name: shipments
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: created      
      - name: shipping_carriers
      - name: shipping_options
      - name: shipping_labels
      - name: supplier_auction_line_items
      - name: supplier_auctions
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: assigned_at      
      - name: supplier_finishes
      - name: supplier_processes
      - name: supplier_rfqs
      - name: supplier_technologies
      - name: supplier_users
      - name: suppliers
      - name: suppliers_material_subsets
      - name: teams
      - name: team_invites
      - name: team_users
      - name: technologies
      - name: tolerances
      - name: transactions
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: created      
      - name: users
      - name: users_roles

  - name: landing
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: load_timestamp
    tables:
      - name: hubspot_deals_dealstage_history_20201125
        freshness: null  # Ignoring freshness for this data source
      - name: freshdesk_agents_landing
      - name: freshdesk_companies_landing
      - name: freshdesk_contacts_landing
      - name: freshdesk_groups_landing
      - name: freshdesk_surveys_landing
      - name: freshdesk_survey_results_landing
      - name: freshdesk_ticket_conversations_landing
      - name: freshdesk_tickets_landing
      - name: freshdesk_tickets_groups_backup_20200401
        freshness: null  # Ignoring freshness for this data source

#########
# TESTS #
#########

models:
  - name: dim_companies
    columns:
      - name: hubspot_company_id
        tests:
          - unique
  - name: dim_contacts
    columns:
      - name: hubspot_contact_id
        tests:
          - unique
  - name: fact_rda_behaviour
    columns:
      - name: sa_uuid
        tests:
          - unique
          - not_null
  - name: fact_line_items
    columns:
      - name: line_item_uuid
        tests:
          - unique
  - name: fact_orders
    columns:
      - name: order_uuid
        tests:
          - unique
