version: 2


###########
# SOURCES #
###########

sources:

  - name: ext_hubspot_webhooks
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: data

  - name: landing
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: load_timestamp
    tables:
      - name: hubspot_deals_dealstage_history_20201125
        freshness: null  # Ignoring freshness for this data source
      - name: freshdesk_agents_landing
      - name: freshdesk_companies_landing
      - name: freshdesk_contacts_landing
      - name: freshdesk_groups_landing
      - name: freshdesk_surveys_landing
      - name: freshdesk_survey_results_landing
      - name: freshdesk_ticket_conversations_landing
      - name: freshdesk_tickets_landing
      - name: freshdesk_tickets_groups_backup_20200401
        freshness: null  # Ignoring freshness for this data source

  - name: _3d_hubs
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: received_at
    tables:
      - name: supply_quote_updated
      - name: frontend_email_wall_submitted

  - name: adwords
    tables:
      - name: click_performance_reports

  - name: ext_adwords
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: accounts
      - name: ad_groups
      - name: ad_groups__labels
      - name: campaigns__labels
      - name: campaign_performance_report
      - name: campaigns
      - name: click_performance_report
      - name: keywords_performance_report

  - name: ext_bing
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: keyword_performance_report
  
  - name: ext_netsuite
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_received_at
    tables:
      - name: currencyrate
      - name: transaction
      - name: transaction__itemlist__item

  - name: data_lake
    tables:
      - name: hubspot_engagements
      - name: hubspot_deals_stitch
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: createdate
      - name: legacy_contacts
      - name: hubspot_contacts_stitch
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: createdate
      - name: hubspot_companies_stitch
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: created_at   
      - name: hubspot_owners
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: load_timestamp
      - name: hubspot_owners_teams
      - name: hubspot_email_wall_submissions_20210423
      - name: hubspot_pages_staging

      - name: exchange_rate_spot_daily
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: load_timestamp

      - name: google_search_console
        freshness:
          warn_after: {count: 5, period: day}
          error_after: {count: 6, period: day}
        loaded_at_field: date
        
      - name: btyd
        freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 14, period: day}
        loaded_at_field: snapshot_date

      - name: supply_countries_markets_mapping

      - name: static_seo_page_group
      - name: static_seo_targets

      - name: adhoc_drupal_closed_sales_20191211
      - name: supply_cross_docking_tracking_details_20200911
      - name: legacy_orders
      - name: freshdesk_groups_legacy_20200401
      - name: dim_dates

  - name: int_greenhubs
    tables:
      - name: co2_emissions

  - name: int_logistics
    tables:
      - name: shipping_customs_information

  - name: int_service_supply
    tables:
      - name: addresses
      - name: auctions
      - name: bids
      - name: bids_bid_reasons
      - name: bid_reasons
      - name: branded_materials
      - name: cancellation_reasons
      - name: cnc_order_parts_inspection_attachments
      - name: cnc_order_quote_attachments
      - name: cnc_orders
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: created
      - name: cnc_order_quotes
      - name: company_entities
      - name: complaint_reasons
      - name: complaint_type_reasons
      - name: complaint_type_reasons_association
      - name: complaint_types
      - name: complaints
      - name: countries
      - name: discount_codes
      - name: discounts
      - name: dispute_issues
      - name: dispute_line_items
      - name: dispute_line_items_issues
      - name: disputes
      - name: lead_time_tiers
      - name: line_items
      - name: matching_scores
      - name: material_colors
      - name: material_finishes
      - name: material_subsets
      - name: material_subsets_region_settings
      - name: materials
      - name: materials_material_finishes
      - name: netsuite_customer_addresses
      - name: netsuite_customers
      - name: netsuite_sales_order
      - name: order_change_requests
      - name: order_delays
      - name: order_history_events
      - name: order_review_answers
      - name: order_review_questions
      - name: packages
      - name: processes
      - name: purchase_orders
      - name: question_groups
      - name: question_types
      - name: questions
      - name: quote_docusign_requests
      - name: refund_reasons
      - name: refund_requests
      - name: refunds
      - name: replies
      - name: reply_options
      - name: shipments
      - name: shipping_carriers
      - name: shipping_options
      - name: supplier_auction_line_items
      - name: supplier_auctions
      - name: supplier_finishes
      - name: supplier_processes
      - name: supplier_rfqs
      - name: supplier_technologies
      - name: supplier_users
      - name: suppliers
      - name: suppliers_material_subsets
      - name: teams
      - name: team_users
      - name: technologies
      - name: tolerances
      - name: transactions
      - name: users
      - name: currencies

  - name: reporting
    tables:
      - name: cube_deals

#########
# TESTS #
#########

models:
  - name: dim_companies
    columns:
      - name: hubspot_company_id
        tests:
          - unique
  - name: dim_contacts
    columns:
      - name: hubspot_contact_id
        tests:
          - unique
  - name: fact_rda_behaviour
    columns:
      - name: sa_uuid
        tests:
          - unique
          - not_null
  - name: fact_line_items
    columns:
      - name: line_item_uuid
        tests:
          - unique
  - name: fact_orders
    columns:
      - name: order_uuid
        tests:
          - unique
