version: 2

models:
  - name: fact_supplier_auction_interactions
    columns:
      - name: supplier_auction_uuid
        tests:
          - unique
          - not_null
  - name: fact_disputes
    columns:
      - name: order_uuid
        tests:
          - unique