version: 2

sources:
  - name: data_lake
    tables:
      - name: hubspot_engagements
      - name: hubspot_deals
      - name: hubspot_contacts
      - name: hubspot_companies
      - name: hubspot_owners
      - name: hubspot_owners_teams

models:
  - name: fact_supplier_auction_interactions
    columns:
      - name: supplier_auction_uuid
        tests:
          - unique
          - not_null
  - name: fact_disputes
    columns:
      - name: order_uuid
        tests:
          - unique
  - name: agg_quote_transactions
    columns:
      - name: quote_uuid
        tests:
          - unique