version: 2

###########
# SOURCES #
###########

sources:
  - name: adwords
    database: INGESTION_SANDBOX_S3
    schema: adwords
    tables:
      - name: click_performance_reports

  - name: dbt_networkservices
    database: INGESTION_SANDBOX_S3
    schema: dbt_networkservices
    tables:
      - name: gold_auctions
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: auction_created_at
      - name: gold_billing_requests
        config:
          freshness:
            warn_after: {count: 31, period: day}
            error_after: {count: 33, period: day}
          loaded_at_field: created_at
      - name: gold_bids
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: created
      - name: gold_complaints
        config:
          freshness:
            warn_after: {count: 4, period: day}
            error_after: {count: 7, period: day}
          loaded_at_field: created_at
      - name: gold_disputes
        config:
          freshness:
            warn_after: {count: 4, period: day}
            error_after: {count: 7, period: day}
          loaded_at_field: created
      - name: gold_discount__line_items
        config:
          freshness:
            warn_after: {count: 4, period: day}
            error_after: {count: 7, period: day}
          loaded_at_field: created_at
      - name: gold_documents
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: created
      - name: gold_external_orders
        config:
          freshness:
            warn_after: {count: 2, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: created_at
      - name: gold_line_items
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: created
      - name: gold_orders
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: created
      - name: gold_order_reviews
        config:
          freshness:
            warn_after: {count: 2, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: created_at
      - name: gold_open_questions
        config:
          freshness:
            warn_after: {count: 7, period: day}
            error_after: {count: 14, period: day}
          loaded_at_field: submitted_at
      - name: gold_order_delays
        config:
          freshness:
            warn_after: {count: 2, period: day}
            error_after: {count: 4, period: day}
          loaded_at_field: created
      - name: gold_order_history_events # Used in a sensitive incremental model
        config:
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}
          loaded_at_field: created
      - name: gold_packages
        config:
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}
          loaded_at_field: created_at
      - name: gold_part_feature_questions
        config:
          freshness:
            warn_after: {count: 7, period: day}
            error_after: {count: 14, period: day}
          loaded_at_field: submitted_at
      - name: gold_quick_link
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: updated_at
      - name: gold_quicklinks_tracking
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: created_at
      - name: gold_questions
        config:
          freshness:
            warn_after: {count: 7, period: day}
            error_after: {count: 14, period: day}
          loaded_at_field: submitted_at
      - name: gold_supplier_auctions
        config:
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}
          loaded_at_field: assigned_at
      - name: gold_shipments
        config:
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}
          loaded_at_field: created
      - name: gold_team_invites
        config:
          freshness:
            warn_after: {count: 3, period: day}
            error_after: {count: 5, period: day}
          loaded_at_field: invite_created_at
      - name: gold_transactions
        config:
          freshness:
            warn_after: {count: 2, period: day}
            error_after: {count: 4, period: day}
          loaded_at_field: created
      - name: gold_users
        config:
          freshness:
            warn_after: {count: 2, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: created_at
  - name: int_analytics
    database: INGESTION_SANDBOX_S3
    schema: int_analytics
    tables:
      - name: btyd
        config:
          freshness:
            warn_after: {count: 7, period: day}
            error_after: {count: 14, period: day}
          loaded_at_field: snapshot_date
      - name: customer_tiering
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: snapshot_at
      - name: delay_probability_v2
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: model_executed_at
      - name: mql_conversion_pred
        config:
          freshness:
            warn_after: {count: 2, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: model_executed_at
      - name: smart_qc
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: model_executed_at
      - name: smart_qc_unique_history
        config:
          freshness:
            warn_after: {count: 2, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: model_executed_at
      - name: dim_dates
      - name: full_order_history_events
        config:
          freshness:
            warn_after:
              count: 1
              period: day
            error_after:
              count: 2
              period: day
          loaded_at_field: created
      - name: legacy_contacts
      - name: legacy_mqls
      - name: legacy_orders
      - name: supply_cross_docking_tracking_details_20200911
      - name: nps_scores
      - name: static_seo_page_group
      - name: static_seo_targets
      - name: supply_countries_markets_mapping

    config:
      tags: ["int_analytics"]
  - name: ext_google_search
    database: INGESTION_SANDBOX_S3
    schema: ext_google_search
    tables:
      - name: search_console
        config:
          freshness:
            warn_after: {count: 5, period: day}
            error_after: {count: 6, period: day}
          loaded_at_field: "date::timestamp"
  - name: dbt_backups
    database: INGESTION_SANDBOX_S3
    schema: dbt_backups
    tables:
      - name: backup_fact_contribution_margin
      - name: backup_fact_orders
      - name: backup_full_order_history_events
      - name: backup_dim_companies
      - name: backup_dim_contacts

  - name: ext_adwords
    database: INGESTION_SANDBOX_S3
    schema: ext_adwords
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: click_performance_report
      - name: keywords_performance_report

  - name: ext_aftership_bv
    database: INGESTION_SANDBOX_S3
    schema: ext_aftership_bv
    tables:
      - name: data
      - name: data__msg__checkpoints

    config:
      freshness:
        warn_after: {count: 12, period: hour}
        error_after: {count: 24, period: hour}
      loaded_at_field: _sdc_received_at
  - name: ext_aftership_llc
    database: INGESTION_SANDBOX_S3
    schema: ext_aftership_llc
    tables:
      - name: data
      - name: data__msg__checkpoints

    config:
      freshness:
        warn_after: {count: 12, period: hour}
        error_after: {count: 24, period: hour}
      loaded_at_field: _sdc_received_at
  - name: ext_bing
    database: INGESTION_SANDBOX_S3
    schema: ext_bing
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: keyword_performance_report

    config:
      freshness:
        warn_after: {count: 12, period: hour}
        error_after: {count: 24, period: hour}
      loaded_at_field: _sdc_received_at
  - name: ext_bing_emea
    database: INGESTION_SANDBOX_S3
    schema: ext_bing_emea
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: keyword_performance_report

    config:
      freshness:
        warn_after: {count: 12, period: hour}
        error_after: {count: 24, period: hour}
      loaded_at_field: _sdc_received_at
  # todo-migration: this source is not available yet, add when ready
  # - name: _ext_bing_factory
  #   loaded_at_field: _sdc_received_at
  #   tables:
  #     - name: accounts
  #     - name: ad_groups
  #     - name: campaign_performance_report
  #     - name: campaigns
  #     - name: keyword_performance_report

    # config:
    #   freshness:
    #     warn_after: {count: 12, period: hour}
    #     error_after: {count: 24, period: hour}

  - name: ext_hubspot_webhooks
    database: INGESTION_SANDBOX_S3
    schema: ext_hubspot_webhooks
    tables:
      - name: data

    config:
      freshness:
        warn_after: {count: 12, period: hour}
        error_after: {count: 24, period: hour}
      loaded_at_field: _sdc_received_at
  - name: ext_google_ads_console
    database: INGESTION_SANDBOX_S3
    schema: ext_google_ads_console
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: click_performance_report
      - name: keywords_performance_report

    config:
      freshness:
        warn_after: {count: 12, period: hour}
        error_after: {count: 24, period: hour}
      loaded_at_field: _sdc_received_at
  - name: ext_gsheets_v2
    database: INGESTION_SANDBOX_S3
    schema: ext_gsheets_v2
    tables:
      - name: marketing_ahrefs
      - name: marketing_share_of_voice
      - name: marketing_youtube
      - name: hr_bamboo_employees
      - name: sdr_commissions

    config:
      loaded_at_field: _sdc_received_at
  - name: ext_hubspot
    database: INGESTION_SANDBOX_S3
    schema: ext_hubspot
    tables:
      - name: contacts
        config:
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
          loaded_at_field: _sdc_received_at
      - name: companies
        config:
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
          loaded_at_field: _sdc_received_at
      - name: hubspot_engagements
        config:
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
          loaded_at_field: load_timestamp
      - name: campaigns
      - name: deals
        config:
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
          loaded_at_field: _sdc_received_at
      - name: deals__associations__associatedcompanyids
      - name: deals__associations__associatedvids
      - name: hubspot_deals_dealstage_history_20201125
      - name: email_events
        config:
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
          loaded_at_field: _sdc_received_at
      - name: hubspot_owners
        config:
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
          loaded_at_field: "load_timestamp"
  - name: ext_netsuite
    database: INGESTION_SANDBOX_S3
    schema: ext_netsuite
    tables:
      - name: currencyrate
      - name: transaction
      - name: customer
      - name: transaction__itemlist__item

    config:
      freshness:
        warn_after: {count: 12, period: hour}
        error_after: {count: 24, period: hour}
      loaded_at_field: _sdc_received_at
  - name: fed_model_repo
    database: INGESTION_SANDBOX_S3
    schema: fed_model_repo
    tables:
      - name: upload

  - name: int_airbyte_controlhub
    database: INGESTION_SANDBOX_S3
    schema: int_airbyte_controlhub
    tables:
      - name: package_scans
      - name: package_messages

  - name: int_greenhubs
    database: INGESTION_SANDBOX_S3
    schema: int_greenhubs
    tables:
      - name: co2_emissions

  - name: int_logistics
    database: INGESTION_SANDBOX_S3
    schema: int_logistics
    tables:
      - name: automated_shipping_customs_information

  - name: int_model_repo_raw
    database: INGESTION_SANDBOX_S3
    schema: int_model_repo_raw
    tables:
      - name: job_ml_geo
      - name: job_machining_quote

  - name: int_retool
    database: INGESTION_SANDBOX_S3
    schema: int_retool
    tables:
      - name: qc_inspections
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: _sdc_batched_at
      - name: inspection_line_items
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: _sdc_batched_at
      - name: dhl_api_documents
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: _sdc_batched_at
      - name: ups_api_documents
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: _sdc_batched_at
      - name: dhl_api_shipment_dimensions
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: _sdc_batched_at
      - name: ups_api_shipment_dimensions
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: _sdc_batched_at
      - name: uk_ups_api_documents
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: _sdc_batched_at
      - name: xdock_holdrack_status


  - name: int_service_supply
    database: INGESTION_SANDBOX_S3
    schema: int_service_supply
    tables:
      - name: countries # Required for a snapshot
      - name: cnc_order_quotes # Required for a snapshot
        config:
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}
          loaded_at_field: created
      - name: new_bids # Required for a snapshot
      - name: suppliers # Required for a snapshot
      - name: supplier_users # Required for a snapshot

  - name: dbt_ingestion
    database: INGESTION_SANDBOX_S3
    schema: dbt_ingestion
    tables:
      - name: gold_ext_airbyte_exchange_rate_daily
        config:
          freshness:
            error_after: {count: 24, period: hour}
          loaded_at_field: date
      - name: gold_ext_airbyte_hubspot_pages
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: date
      - name: gold_ext_airbyte_freshdesk_tickets
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: _load_timestamp
      - name: gold_ext_airbyte_freshdesk_survey_results
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}
          loaded_at_field: load_timestamp
  - name: ext_freshdesk
    database: INGESTION_SANDBOX_S3
    schema: ext_freshdesk
    tables:
      - name: freshdesk_ticket_conversations
      - name: freshdesk_tickets_groups_backup_20200401
        config:
          freshness:
      - name: freshdesk_groups_legacy_20200401
        config:
          freshness:
    config:
      freshness:
        warn_after: {count: 24, period: hour}
        error_after: {count: 48, period: hour}
      loaded_at_field: load_timestamp
models:
  - name: dim_companies
    columns:
      - name: hubspot_company_id
        tests:
          - unique
  - name: dim_contacts
    columns:
      - name: hubspot_contact_id
        tests:
          - unique
  - name: fact_auction_behaviour
    columns:
      - name: sa_uuid
        tests:
          - unique
          - not_null
  - name: fact_line_items
    columns:
      - name: line_item_uuid
        tests:
          - unique
  - name: fact_orders
    columns:
      - name: order_uuid
        tests:
          - unique