version: 2

###########
# SOURCES #
###########

sources:
  - name: adwords
    tables:
      - name: click_performance_reports

  - name: int_analytics
    tags: ["int_analytics"]
    tables:
      - name: btyd
        freshness:
          warn_after: { count: 7, period: day }
          error_after: { count: 14, period: day }
        loaded_at_field: snapshot_date
      - name: customer_tiering
        freshness:
          warn_after: { count: 1, period: day }
          error_after: { count: 2, period: day }
        loaded_at_field: snapshot_at
      - name: delay_probability
        freshness:
          warn_after: { count: 1, period: day }
          error_after: { count: 2, period: day }
        loaded_at_field: model_executed_at
      - name: mql_conversion_pred
        freshness:
          warn_after: { count: 2, period: day }
          error_after: { count: 3, period: day }
        loaded_at_field: model_executed_at
      - name: smart_qc
        freshness:
          warn_after: { count: 1, period: day }
          error_after: { count: 2, period: day }
        loaded_at_field: model_executed_at
      - name: dim_dates
      - name: exchange_rate_spot_daily
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: date
      - name: full_order_history_events
      - name: legacy_contacts
      - name: legacy_mqls
      - name: legacy_orders
      - name: supply_cross_docking_tracking_details_20200911
      - name: nps_scores
      - name: static_seo_page_group
      - name: static_seo_targets
      - name: supply_countries_markets_mapping
      
  - name: ext_google_search
    tables:
      - name: search_console
        freshness:
          warn_after: { count: 5, period: day }
          error_after: { count: 6, period: day }
        loaded_at_field: "date::timestamp"

  - name: dbt_backups
    tables:
      - name: backup_fact_contribution_margin
      - name: backup_fact_orders
      - name: backup_full_order_history_events
      - name: backup_dim_companies
      - name: backup_dim_contacts

  - name: ext_adwords
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: click_performance_report
      - name: keywords_performance_report

  - name: ext_aftership_bv
    freshness:
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: _sdc_received_at
    tables:
      - name: data
      - name: data__msg__checkpoints

  - name: ext_aftership_llc
    freshness:
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: _sdc_received_at
    tables:
      - name: data
      - name: data__msg__checkpoints

  - name: ext_bing
    freshness:
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: _sdc_received_at
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: keyword_performance_report

  - name: ext_hubspot_webhooks
    freshness:
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: _sdc_received_at
    tables:
      - name: data

  - name: fed_publicapi
    tables:
      - name: quick_link

  - name: fed_fulfilment
    tables:
      - name: questions
      - name: replies
      - name: reply_options
      - name: open_questions
      - name: part_feature_questions      

  - name: ext_google_ads_console
    freshness:
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: _sdc_received_at
    tables:
      - name: accounts
      - name: ad_groups
      - name: campaign_performance_report
      - name: campaigns
      - name: click_performance_report
      - name: keywords_performance_report

  - name: ext_gsheets_v2
    loaded_at_field: _sdc_received_at
    tables:
      - name: marketing_ahrefs
      - name: marketing_share_of_voice
      - name: marketing_youtube
      - name: hr_bamboo_employees
      - name: sdr_commissions

  - name: ext_hubspot
    tables:
      - name: contacts
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: _sdc_received_at
      - name: companies
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: _sdc_received_at
      - name: hubspot_engagements
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: load_timestamp
      - name: campaigns
      - name: deals
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: _sdc_received_at
      - name: deals__associations__associatedcompanyids
      - name: deals__associations__associatedvids
      - name: hubspot_deals_dealstage_history_20201125
      - name: email_events
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: _sdc_received_at
      - name: hubspot_pages
        freshness:
          warn_after: { count: 48, period: hour }
          error_after: { count: 72, period: hour }
        loaded_at_field: "date::timestamp"
      - name: hubspot_owners
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: "load_timestamp"

  - name: ext_netsuite
    freshness:
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: _sdc_received_at
    tables:
      - name: currencyrate
      - name: transaction
      - name: customer
      - name: transaction__itemlist__item

  - name: int_greenhubs
    tables:
      - name: co2_emissions

  - name: int_logistics
    tables:
      - name: automated_shipping_customs_information

  #   - name: fed_service_supply
  #    tables:
  #      - name: line_items

  - name: int_service_supply
    tables:
      - name: addresses
      - name: anonymous_user_carts
      - name: auctions
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: started_at
      - name: new_bids
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: placed_at
      - name: batch_shipment_line_items
      - name: batch_shipments
      - name: batch_package_line_items
      - name: bids
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: placed_at
      - name: new_bids_bid_reasons
      - name: bid_reasons
      - name: billing_requests
        freshness:
          warn_after: { count: 31, period: day }
          error_after: { count: 33, period: day }
        loaded_at_field: created
      - name: branded_materials
      - name: cancellation_reasons
      - name: cnc_order_parts_inspection_attachments
      - name: cnc_orders
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: created
      - name: cnc_order_quotes
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: created
      - name: commodity_code_customs_rates
      - name: company_entities
      - name: complaint_reasons
      - name: complaint_type_reasons
      - name: complaint_type_reasons_association
      - name: complaint_types
      - name: complaints
        freshness:
          warn_after: { count: 4, period: day }
          error_after: { count: 7, period: day }
        loaded_at_field: created
      - name: countries
      - name: currencies
      - name: discount_codes
      - name: discounts
      - name: dispute_issues
      - name: dispute_line_items
      - name: dispute_line_items_issues
      - name: disputes
        freshness:
          warn_after: { count: 4, period: day }
          error_after: { count: 7, period: day }
        loaded_at_field: created
      - name: external_orders
        freshness: null # To be added when more volume
        loaded_at_field: created
      - name: financial_settings
      - name: lead_time_tiers
      - name: line_items
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: created
      - name: line_item_virtual_quality_control_part_photos
      - name: matching_scores
      - name: material_colors
      - name: material_finishes
      - name: material_subsets
      - name: material_subsets_region_settings
      - name: material_types
      - name: materials
      - name: materials_material_finishes
      - name: netsuite_customers
      - name: order_change_requests
      - name: order_delays
        freshness:
          warn_after: { count: 2, period: day }
          error_after: { count: 4, period: day }
        loaded_at_field: created
      - name: order_history_events
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: created
      - name: order_review_answers
      - name: order_review_questions
      - name: packages
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: created
      - name: package_line_items
      - name: processes
      - name: purchase_orders
      - name: question_groups
      - name: quicklinks_tracking
      - name: quote_docusign_requests
      - name: refund_reasons
      - name: refund_requests
      - name: refunds
      - name: roles
      - name: sales_rfqs
      - name: shipments
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: created
      - name: shipping_carriers
      - name: shipping_options
      - name: shipping_labels
      - name: supplier_auction_line_items
      - name: supplier_auctions
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: assigned_at
      - name: supplier_finishes
      - name: supplier_processes
      - name: supplier_rfqs
      - name: supplier_technologies
      - name: supplier_users
      - name: suppliers
      - name: suppliers_material_subsets
      - name: teams
      - name: team_invites
      - name: team_users
      - name: technologies
      - name: tolerances
      - name: transactions
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: created
      - name: users
      - name: users_roles
      - name: virtual_quality_control_order_packaging_photos

  - name: ext_freshdesk
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: load_timestamp
    tables:
      - name: freshdesk_agents
      - name: freshdesk_companies
      - name: freshdesk_contacts
      - name: freshdesk_groups
      - name: freshdesk_surveys
      - name: freshdesk_survey_results
      - name: freshdesk_ticket_conversations
      - name: freshdesk_tickets
      - name: freshdesk_tickets_groups_backup_20200401
        freshness: null  # Ignoring freshness for this data source
      - name: freshdesk_groups_legacy_20200401
        freshness: null  # Ignoring freshness for this data source

#########
# TESTS #
#########

models:
  - name: dim_companies
    columns:
      - name: hubspot_company_id
        tests:
          - unique
  - name: dim_contacts
    columns:
      - name: hubspot_contact_id
        tests:
          - unique
  - name: fact_auction_behaviour
    columns:
      - name: sa_uuid
        tests:
          - unique
          - not_null
  - name: fact_line_items
    columns:
      - name: line_item_uuid
        tests:
          - unique
  - name: fact_orders
    columns:
      - name: order_uuid
        tests:
          - unique
