version: 2

sources:
  - name: data_lake
    tables:
      - name: hubspot_engagements
      - name: hubspot_deals
      - name: hubspot_contacts
      - name: hubspot_companies
      - name: hubspot_owners
      - name: hubspot_owners_teams
      - name: exchange_rate_spot_daily
        freshness:
          warn_after: {count: 2, period: day}
        loaded_at_field: load_timestamp

  - name: int_service_supply
    tables:
      - name: dispute_line_items_issues

models:
  - name: fact_supplier_auction_interactions
    columns:
      - name: supplier_auction_uuid
        tests:
          - unique
          - not_null
  - name: fact_disputes
    columns:
      - name: order_uuid
        tests:
          - unique
  - name: agg_quote_transactions
    columns:
      - name: quote_uuid
        tests:
          - unique